---
title: Is in Town
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: false
url: https://www.isintown.com
description: Is in Town is a bi-annual magazine featuring the most interesting new
  faces. The girls are collaborators and their stories make the pictures.
permalink: pretty
exclude:
- bower.json
- Gemfile.lock
- package.json
- config.codekit3
- README*
- LICENSE*
- CHANGELOG*
- node_modules
- ".gitignore"
- bower_components
- assets/scss
plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
email: info@isintown.com
subscribe: 
analytics: UA-99920545-1
logo: "/assets/img/logo.svg"
per_page: 12
date_format: "%b %d, %Y"
future: true
compress_html:
  comments:
  - "<!-- "
  - " -->"
  blanklines: true
  profile: false
