---
title: Is in Town
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: false
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/journal/:title/"
url: http://isintown.com
description: Is in Town is a bi-annual magazine featuring the most interesting new
  faces. The girls are collaborators and their stories make the pictures.
buy: https://www.antennebooks.com/
permalink: pretty
exclude:
- Gemfile
- Gemfile.lock
- bower.json
- package.json
- config.codekit3
- README*
- LICENSE*
- CHANGELOG*
- node_modules
- ".gitignore"
- bower_components
gems:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
colophon: http://garethjohnsdesign.com
company: Is in Town
email: info@isintown.com
google_site_verification: 
analytics: 
logo: "/assets/img/logo.svg"
per_page: 12
date_format: "%d %B %Y"
future: true
social:
  facebook: https://www.facebook.com/
  instagram: https://www.instagram.com/
  twitter: https://www.twitter.com/
  soundcloud: https://soundcloud.com/
compress_html:
  comments:
  - "<!-- "
  - " -->"
  blanklines: true
  profile: false
